#!/bin/bash
# setup-secrets.sh - Setup GitHub Actions and Vercel secrets
# Run this script to configure deployment secrets

set -e

echo "========================================"
echo "EXO ProTrack - Secret Setup"
echo "========================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running in GitHub Actions
if [ -n "$GITHUB_ACTIONS" ]; then
    echo -e "${GREEN}Running in GitHub Actions${NC}"
fi

# Function to read input with default
read_input() {
    local prompt="$1"
    local default="$2"
    local is_password="${3:-false}"
    
    if [ "$is_password" = true ]; then
        read -s -p "$prompt [$default]: " value
        echo ""
        if [ -z "$value" ]; then
            echo "$default"
        else
            echo "$value"
        fi
    else
        read -p "$prompt [$default]: " value
        if [ -z "$value" ]; then
            echo "$default"
        else
            echo "$value"
        fi
    fi
}

# Supabase Configuration
echo -e "${YELLOW}Supabase Configuration${NC}"
echo "-----------------------------------"
SUPABASE_URL=$(read_input "Supabase URL" "https://your-project.supabase.co")
SUPABASE_ANON_KEY=$(read_input "Supabase Anon Key" "" true)
echo ""

# Vercel Configuration
echo -e "${YELLOW}Vercel Configuration${NC}"
echo "-----------------------------------"
VERCEL_TOKEN=$(read_input "Vercel Token" "" true)
VERCEL_ORG_ID=$(read_input "Vercel Org ID" "")
VERCEL_PROJECT_ID=$(read_input "Vercel Project ID" "")
echo ""

# Generate .env.local file
echo -e "${GREEN}Generating .env.local...${NC}"
cat > exo-protrack/.env.local << EOF
# Local development environment variables
# Generated by setup-secrets.sh

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
EOF

echo "Created: exo-protrack/.env.local"

# Generate GitHub Actions secrets template
echo -e "${GREEN}Generating GitHub Actions secrets template...${NC}"
cat > .github/secrets-template.env << EOF
# GitHub Actions Secrets Template
# Copy to GitHub Repository > Settings > Secrets and Variables > Actions

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
VERCEL_TOKEN=$VERCEL_TOKEN
VERCEL_ORG_ID=$VERCEL_ORG_ID
VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID
EOF

echo "Created: .github/secrets-template.env"
echo ""

# Generate Vercel environment file
echo -e "${GREEN}Generating Vercel env file...${NC}"
cat > vercel.env.json << EOF
{
  "env": {
    "VITE_SUPABASE_URL": "$SUPABASE_URL",
    "VITE_SUPABASE_ANON_KEY": "$SUPABASE_ANON_KEY"
  }
}
EOF

echo "Created: vercel.env.json"
echo ""

# Summary
echo "========================================"
echo -e "${GREEN}Setup Complete!${NC}"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Add secrets to GitHub:"
echo "   - Repository > Settings > Secrets and Variables > Actions"
echo "   - Add all variables from .github/secrets-template.env"
echo ""
echo "2. Deploy to Vercel:"
echo "   - Import repository in Vercel Dashboard"
echo "   - Add environment variables in Project Settings"
echo "   - Deploy!"
echo ""
echo "3. For Supabase:"
echo "   - Run migrations in supabase/migrations/"
echo "   - Deploy edge functions"
echo ""
