<#
.SYNOPSIS
    EXO ProTrack - Complete Setup Script
.DESCRIPTION
    Автоматическая настройка GitHub, Supabase и Vercel для EXO ProTrack
.PARAMETER Interactive
    Запрашивать токены интерактивно (по умолчанию)
.PARAMETER SupabaseUrl
    Supabase URL (если не интерактивный режим)
.PARAMETER SupabaseKey
    Supabase anon key (если не интерактивный режим)
.PARAMETER VercelToken
    Vercel API token (если не интерактивный режим)
.EXAMPLE
    .\setup.ps1
    .\setup.ps1 -SupabaseUrl "https://xxx.supabase.co" -SupabaseKey "xxx" -VercelToken "xxx"
#>

param(
    [switch]$Interactive = $true,
    [string]$SupabaseUrl = "",
    [string]$SupabaseKey = "",
    [string]$VercelToken = "",
    [string]$GitHubToken = ""
)

$ErrorActionPreference = "Stop"

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  EXO ProTrack - Complete Setup" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# Colors
$Green = [ConsoleColor]::Green
$Yellow = [ConsoleColor]::Yellow
$Red = [ConsoleColor]::Red
$White = [ConsoleColor]::White

function Write-Success {
    param([string]$Message)
    Write-Host "[✓] " -ForegroundColor $Green -NoNewline
    Write-Host $Message -ForegroundColor $White
}

function Write-Warning {
    param([string]$Message)
    Write-Host "[!] " -ForegroundColor $Yellow -NoNewline
    Write-Host $Message -ForegroundColor $White
}

function Write-Error {
    param([string]$Message)
    Write-Host "[✗] " -ForegroundColor $Red -NoNewline
    Write-Host $Message -ForegroundColor $White
}

function Read-Secure {
    param([string]$Prompt, [string]$Default = "")
    $secure = Read-Host $Prompt -AsSecureString
    if ($secure.Length -eq 0 -and $Default) {
        return $Default
    }
    return [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
}

function Read-Input {
    param([string]$Prompt, [string]$Default = "")
    $value = Read-Host $Prompt
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }
    return $value
}

# Get tokens
if ($Interactive) {
    Write-Host "Настройка Supabase:" -ForegroundColor $Yellow
    Write-Host "-----------------------------------" -ForegroundColor $Yellow
    $SupabaseUrl = Read-Input "Supabase URL (https://xxx.supabase.co)" "https://your-project.supabase.co"
    $SupabaseKey = Read-Secure "Supabase Anon Key"
    Write-Host ""
    
    Write-Host "Настройка Vercel:" -ForegroundColor $Yellow
    Write-Host "-----------------------------------" -ForegroundColor $Yellow
    $VercelToken = Read-Secure "Vercel API Token"
    Write-Host ""
    
    Write-Host "Настройка GitHub (опционально):" -ForegroundColor $Yellow
    Write-Host "-----------------------------------" -ForegroundColor $Yellow
    $GitHubToken = Read-Secure "GitHub Personal Access Token (оставьте пустым для пропуска)" ""
    Write-Host ""
}

# Check for existing CLI tools
Write-Host "Проверка инструментов..." -ForegroundColor $Yellow

$cliTools = @{
    "node" = @{
        "check" = { node --version }
        "install" = "https://nodejs.org"
    }
    "gh" = @{
        "check" = { gh --version }
        "install" = "https://cli.github.com"
    }
    "supabase" = @{
        "check" = { supabase --version }
        "install" = "npm install -g supabase"
    }
    "vercel" = @{
        "check" = { vercel --version }
        "install" = "npm i -g vercel"
    }
}

$installedTools = @()

foreach ($tool in $cliTools.GetEnumerator()) {
    try {
        $null = & $tool.Value.check 2>&1
        Write-Success "$($tool.Key) установлен"
        $installedTools += $tool.Key
    } catch {
        Write-Warning "$($tool.Key) не найден"
    }
}

Write-Host ""

# Step 1: Create .env.local
Write-Host "Шаг 1/5: Создание .env.local..." -ForegroundColor $Yellow
try {
    $envContent = @"
# Local development environment variables
# Generated by setup.ps1
# $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

VITE_SUPABASE_URL=$SupabaseUrl
VITE_SUPABASE_ANON_KEY=$SupabaseKey
"@
    $envContent | Out-File -FilePath "exo-protrack/.env.local" -Encoding UTF8 -NoNewline
    Write-Success "Создан: exo-protrack/.env.local"
} catch {
    Write-Error "Ошибка создания .env.local: $_"
}

# Step 2: Setup GitHub Secrets
Write-Host ""
Write-Host "Шаг 2/5: Настройка GitHub Secrets..." -ForegroundColor $Yellow

if ($GitHubToken -and $GitHubToken.Length -gt 0) {
    try {
        # Set GitHub token
        $env:GITHUB_TOKEN = $GitHubToken
        
        # Install gh CLI if not present
        if ("gh" -notin $installedTools) {
            Write-Warning "Установите GitHub CLI: https://cli.github.com"
        } else {
            # Set secrets
            $secrets = @{
                "VITE_SUPABASE_URL" = $SupabaseUrl
                "VITE_SUPABASE_ANON_KEY" = $SupabaseKey
                "VERCEL_TOKEN" = $VercelToken
            }
            
            foreach ($secret in $secrets.GetEnumerator()) {
                $null = gh secret set $secret.Key --body $secret.Value 2>&1
                Write-Success "Установлен секрет: $($secret.Key)"
            }
        }
    } catch {
        Write-Warning "Не удалось настроить GitHub Secrets: $_"
        Write-Host "  Добавьте secrets вручную в GitHub Repository > Settings > Secrets" -ForegroundColor $Yellow
    }
} else {
    Write-Warning "GitHub токен не предоставлен"
    Write-Host "  Для авто-настройки GitHub Secrets добавьте токен" -ForegroundColor $Yellow
}

# Step 3: Setup Supabase
Write-Host ""
Write-Host "Шаг 3/5: Настройка Supabase..." -ForegroundColor $Yellow

if ($SupabaseUrl -and $SupabaseUrl.Contains("supabase.co")) {
    try {
        if ("supabase" -notin $installedTools) {
            Write-Warning "Supabase CLI не установлен. Установите: npm install -g supabase"
            Write-Host "  Затем выполните: supabase link --project-ref YOUR_PROJECT_REF" -ForegroundColor $Yellow
            Write-Host "  И: supabase db push" -ForegroundColor $Yellow
        } else {
            # Extract project ref from URL
            $projectRef = $SupabaseUrl -replace 'https://','' -replace '.supabase.co',''
            
            Write-Success "Project Ref: $projectRef"
            Write-Host "  Для применения миграций выполните:" -ForegroundColor $Yellow
            Write-Host "  supabase link --project-ref $projectRef" -ForegroundColor $Yellow
            Write-Host "  supabase db push" -ForegroundColor $Yellow
        }
    } catch {
        Write-Error "Ошибка настройки Supabase: $_"
    }
} else {
    Write-Warning "Некорректный Supabase URL"
}

# Step 4: Setup Vercel
Write-Host ""
Write-Host "Шаг 4/5: Настройка Vercel..." -ForegroundColor $Yellow

if ($VercelToken) {
    try {
        if ("vercel" -notin $installedTools) {
            Write-Warning "Vercel CLI не установлен"
            Write-Host "  Установите: npm i -g vercel" -ForegroundColor $Yellow
            Write-Host "  Затем: cd exo-protrack && vercel --prod" -ForegroundColor $Yellow
        } else {
            $env:VERCEL_TOKEN = $VercelToken
            Write-Success "Vercel CLI готов к использованию"
            Write-Host "  Выполните: cd exo-protrack && vercel --prod" -ForegroundColor $Yellow
        }
    } catch {
        Write-Error "Ошибка настройки Vercel: $_"
    }
} else {
    Write-Warning "Vercel токен не предоставлен"
}

# Step 5: Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Настройка завершена!" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

Write-Host "Что было сделано:" -ForegroundColor $White
Write-Host "  ✓ Создан файл .env.local" -ForegroundColor $Green
if ($GitHubToken) {
    Write-Host "  ✓ GitHub Secrets готовы" -ForegroundColor $Green
} else {
    Write-Host "  ⚠ GitHub Secrets - требуется ручная настройка" -ForegroundColor $Yellow
}
Write-Host "  ⚠ Supabase миграции - требуется apply" -ForegroundColor $Yellow
Write-Host "  ⚠ Vercel деплой - требуется ручной запуск" -ForegroundColor $Yellow

Write-Host ""
Write-Host "Следующие шаги:" -ForegroundColor $Yellow
Write-Host "1. Примените Supabase миграции:" -ForegroundColor $White
Write-Host "   supabase link --project-ref YOUR_PROJECT_REF" -ForegroundColor Cyan
Write-Host "   supabase db push" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. Задеплойте на Vercel:" -ForegroundColor $White
Write-Host "   cd exo-protrack" -ForegroundColor Cyan
Write-Host "   vercel --prod" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. Или используйте GitHub Actions (после настройки secrets)" -ForegroundColor $White
Write-Host "   Просто запушьте код в main ветку" -ForegroundColor $White

Write-Host ""
Write-Host "Документация: DEPLOY_SETUP.md" -ForegroundColor $Yellow
Write-Host ""

# Optional: Open GitHub repo
if ($GitHubToken) {
    $openRepo = Read-Input "Открыть GitHub репозиторий в браузере? (y/N)" "n"
    if ($openRepo.ToLower() -eq "y") {
        Start-Process "https://github.com/bioen07-del/ExoProTrack_new/settings/secrets/actions"
    }
}
