CREATE TABLE collection_event (
    collection_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cm_lot_id VARCHAR(50) NOT NULL,
    culture_id VARCHAR(100) NOT NULL,
    collected_at TIMESTAMPTZ DEFAULT NOW(),
    enrichment_start_date DATE,
    enrichment_end_date DATE,
    passage_no INTEGER NOT NULL,
    cultivation_day INTEGER,
    morphology VARCHAR(20) CHECK (morphology IN ('Excellent',
    'Standard',
    'Deviations',
    'Atypical')),
    confluence_start_percent DECIMAL(5,2),
    confluence_end_percent DECIMAL(5,2),
    volume_ml DECIMAL(10,2) NOT NULL,
    target_container_id UUID NOT NULL,
    operator_user_id UUID,
    media_spec_id UUID NOT NULL,
    media_prep_journal_no VARCHAR(100) NOT NULL,
    media_prep_journal_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);